services:
  redpanda:
    image: redpandadata/redpanda:v26.1.4
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '1'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
      - --rpc-addr
      - 0.0.0.0:33145
      - --advertise-rpc-addr
      - redpanda:33145
    ports:
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092

  redpanda-console:
    image: redpandadata/console:v3.7.1
    restart: unless-stopped
    depends_on:
      - redpanda
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: redpanda:29092

  jobmanager:
    build:
      context: .
      dockerfile: ./Dockerfile.flink
    image: flink
    pull_policy: never
    restart: unless-stopped
    expose:
      - "6123"
    ports:
      - "8081:8081"
    volumes:
      - ./:/opt/flink/usrlib
      - ./src/:/opt/src
      - flink-logs:/opt/flink/log
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.memory.process.size: 1600m
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE

  taskmanager:
    image: flink
    pull_policy: never
    restart: unless-stopped
    expose:
      - "6121"
      - "6122"
    volumes:
      - ./:/opt/flink/usrlib
      - ./src/:/opt/src
      - flink-logs:/opt/flink/log
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.memory.process.size: 1728m
        taskmanager.numberOfTaskSlots: 15
        taskmanager.registration.timeout: 5 min
        parallelism.default: 3
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    

  timescaledb:
    image: timescale/timescaledb:2.26.3-pg18
    restart: on-failure
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: your_secure_password
      MB_DB_HOST: metabase-db
    depends_on:
      - metabase-db
    restart: unless-stopped

  metabase-db:
    image: postgres:15-alpine
    container_name: metabase-db
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - metabase_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  flink-logs:
  metabase_data: